// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:dataBackup': typeof import('~icons/carbon/data-backup')['default']
    'Carbon:dataShare': typeof import('~icons/carbon/data-share')['default']
    'Carbon:delete': typeof import('~icons/carbon/delete')['default']
    'Carbon:licenseMaintenance': typeof import('~icons/carbon/license-maintenance')['default']
    'Carbon:reset': typeof import('~icons/carbon/reset')['default']
    'Carbon:rotate360': typeof import('~icons/carbon/rotate360')['default']
    'Carbon:sendAlt': typeof import('~icons/carbon/send-alt')['default']
    'Carbon:taskTools': typeof import('~icons/carbon/task-tools')['default']
    'Carbon:translate': typeof import('~icons/carbon/translate')['default']
    LockFunc: typeof import('./components/LockFunc.vue')['default']
    QuicklyInstall: typeof import('./components/function/QuicklyInstall.vue')['default']
    Sider: typeof import('./components/Sider.vue')['default']
  }
}

export { }
